import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobalWrapper } from "./global-wrapper";
import StyledComponentsRegistry from "@/lib/registry";

/**
 * RootLayout은 Next.js 애플리케이션의 루트 레이아웃을 정의합니다.
 * HTML 구조, 글로벌 폰트, 글로벌 컨텍스트 및 스타일 적용의 최상단 엔트리 포인트입니다.
 *
 * RootLayout defines the root layout of the Next.js application.
 * It includes the base HTML structure, global fonts, and wraps the app with global context and styles.
 */

// ✅ Google Fonts 설정 | Configure Google Fonts with CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ 페이지 메타데이터 | Page metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

// ✅ 레이아웃 컴포넌트 | Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* body className에서 폰트 변수 제거 */}
      <body className="antialiased">
        {/* StyledComponentsRegistry로 GlobalWrapper와 children 감싸기 */}
        <StyledComponentsRegistry>
          <GlobalWrapper>{children}</GlobalWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

